language: objective-c
osx_image: xcode9.2
env:
  global:
    - WORKSPACE='NEUPagingSegmentedControl.xcworkspace'
    - FRAMEWORK='NEUPagingSegmentedControl-iOS'
    - EXAMPLE='Example'
before_install:
  - export LANG=en_US.UTF-8
install:
  - bundle install --without development --deployment --jobs=3 --retry=3
  - bundle exec pod install
script:
  - set -o pipefail
  - xcodebuild -workspace "$WORKSPACE" -scheme "$FRAMEWORK" -sdk iphonesimulator clean build analyze | xcpretty -c
  - xcodebuild -workspace "$WORKSPACE" -scheme "$EXAMPLE" -sdk iphonesimulator clean build analyze | xcpretty -c
  - carthage build --no-skip-current --verbose | xcpretty -c
notifications:
  email: false
  slack:
    rooms:
      secure: FqlBShTSNHjbQogI4b2Lswzg6WaOb973tY14jHC281oKncE2fLVaSyE8psdeyhFG0RMwU7o6QKkM47FhN5efT6uwgdNehwGnJ0nD6c0F7waqOqHkcixZzY9REbvFMEKdTtD+7Q/lz3ZmR7rdrfpxbQMK0Naj0ynLMgDLTWpR47E=
