language: objective-c
before_script:
  - "export LANG=en_US.UTF-8"
  - "cd Demo"
script:
  - "xctool -workspace NEUPagingSegmentedControlDemo.xcworkspace -scheme NEUPagingSegmentedControlDemo -sdk iphonesimulator clean build"
