language: objective-c
before_install:
  - if test -z $(brew list | grep -i xcproj); then brew install xcproj; fi
before_script:
  - export LANG=en_US.UTF-8
script:
  - xctool -workspace NEUPagingSegmentedControl.xcworkspace -scheme NEUPagingSegmentedControl-iOS -sdk iphonesimulator clean build
  - xctool -workspace NEUPagingSegmentedControl.xcworkspace -scheme Example -sdk iphonesimulator clean build
