language: objective-c
before_install:
  - "brew update; brew upgrade xctool"
  - "gem install cocoapods --no-rdoc --no-ri"
before_script:
  - "export LANG=en_US.UTF-8"
  - "cd Demo"
script:
  - "xctool -project NEUPagingSegmentedControlDemo.xcodeproj -scheme NEUPagingSegmentedControlDemo -sdk iphonesimulator build"
