language: objective-c
before_install:
  - "if test -z $(brew list | grep -i xcproj); then brew install xcproj; fi"
  - "cd Demo"
before_script:
  - "export LANG=en_US.UTF-8"
script:
  - "xctool -workspace NEUPagingSegmentedControlDemo.xcworkspace -scheme NEUPagingSegmentedControlDemo -sdk iphonesimulator clean build"
